CREATE TABLE IF NOT EXISTS channels (
    id INTEGER PRIMARY KEY,
    sticky_id INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS entities (
    pk INTEGER PRIMARY KEY,
    id INTEGER NOT NULL,
    channel_id INTEGER NOT NULL,
    name STRING NOT NULL,
    location_pk INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS locations (
    pk INTEGER PRIMARY KEY,
    id INTEGER NOT NULL,
    channel_id INTEGER NOT NULL,
    name STRING NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);